/**
 * Southeast Produk - AI Engine
 * Sistem AI dengan RAG (Retrieval-Augmented Generation)
 */

class AIEngine {
    constructor() {
        this.ragIndex = null;
        this.contextWindow = 4096;
        this.models = {};
        this.prompts = [];
        this.projects = [];
    }

    async loadRAGIndex() {
        try {
            const response = await fetch('/rag/rag_index.json');
            this.ragIndex = await response.json();
            console.log(`✓ Loaded RAG Index: ${this.ragIndex.total_files} files, ${this.ragIndex.total_lines} lines`);
            return this.ragIndex;
        } catch (error) {
            console.error('Failed to load RAG index:', error);
            return null;
        }
    }

    async retrieveKnowledge(query, category = null, topK = 5) {
        if (!this.ragIndex) await this.loadRAGIndex();
        
        const results = [];
        const queryLower = query.toLowerCase();
        
        for (const file of this.ragIndex.files) {
            if (category && file.category !== category) continue;
            
            try {
                const response = await fetch(`/rag/${file.filename}`);
                const data = await response.json();
                
                for (const line of data.content) {
                    if (line.toLowerCase().includes(queryLower)) {
                        results.push({
                            source: file.filename,
                            category: file.category,
                            content: line,
                            relevance: this.calculateRelevance(query, line)
                        });
                    }
                }
            } catch (e) {
                continue;
            }
        }
        
        return results
            .sort((a, b) => b.relevance - a.relevance)
            .slice(0, topK);
    }

    calculateRelevance(query, text) {
        const queryWords = query.toLowerCase().split(/\s+/);
        const textLower = text.toLowerCase();
        let score = 0;
        
        for (const word of queryWords) {
            if (textLower.includes(word)) score += 1;
        }
        
        return score / queryWords.length;
    }

    async generateResponse(prompt, context = []) {
        const knowledge = await this.retrieveKnowledge(prompt);
        
        return {
            prompt: prompt,
            context: knowledge,
            response: this.synthesizeResponse(prompt, knowledge),
            timestamp: new Date().toISOString(),
            model: 'southeast-ai-v1'
        };
    }

    synthesizeResponse(prompt, knowledge) {
        if (knowledge.length === 0) {
            return "Maaf, saya tidak menemukan informasi yang relevan dalam basis pengetahuan.";
        }
        
        let response = `Berdasarkan ${knowledge.length} sumber pengetahuan:\n\n`;
        knowledge.forEach((item, idx) => {
            response += `${idx + 1}. [${item.category}] ${item.content}\n`;
        });
        
        return response;
    }

    createProject(name, description, requirements = []) {
        const project = {
            id: `proj_${Date.now()}`,
            name,
            description,
            requirements,
            status: 'initiated',
            createdAt: new Date().toISOString(),
            files: [],
            tasks: []
        };
        
        this.projects.push(project);
        return project;
    }

    async generateProjectCode(project) {
        const codeFiles = [];
        
        for (const req of project.requirements) {
            const knowledge = await this.retrieveKnowledge(req, 'kode', 3);
            codeFiles.push({
                name: `${req.replace(/\s+/g, '_').toLowerCase()}.js`,
                content: this.generateCodeFromKnowledge(req, knowledge)
            });
        }
        
        project.files = codeFiles;
        project.status = 'generated';
        return project;
    }

    generateCodeFromKnowledge(requirement, knowledge) {
        return `/**
 * Generated by Southeast Produk AI Engine
 * Requirement: ${requirement}
 */

// Knowledge-based implementation
${knowledge.map(k => `// Source: ${k.source} - ${k.content}`).join('\n')}

module.exports = {
    init: function() {
        console.log('Initialized: ${requirement}');
    }
};`;
    }

    addPrompt(text, category = 'general') {
        this.prompts.push({
            id: `prompt_${this.prompts.length}`,
            text,
            category,
            timestamp: new Date().toISOString()
        });
        return this.prompts[this.prompts.length - 1];
    }

    getPrompts(category = null) {
        if (!category) return this.prompts;
        return this.prompts.filter(p => p.category === category);
    }
}

// Export untuk browser dan Node.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = AIEngine;
} else {
    window.AIEngine = AIEngine;
}
